-- changeset Ralf Ueberfuhr:17526426780011-2
CREATE TABLE ADDRESSES (
  UUID UUID NOT NULL,
  STREET VARCHAR(100),
  NUMBER VARCHAR(255),
  CITY VARCHAR(100) NOT NULL,
  ZIP VARCHAR(5),
  CONSTRAINT PK_ADDRESSES PRIMARY KEY (UUID)
);

ALTER TABLE IF EXISTS CUSTOMERS
  ADD ADDRESS_UUID UUID;
ALTER TABLE IF EXISTS CUSTOMERS
  ADD CONSTRAINT UNIQUE_CUSTOMERS_ADDRESS UNIQUE (address_uuid);
ALTER TABLE IF EXISTS CUSTOMERS
  ADD CONSTRAINT FK_CUSTOMERS_ADDRESS FOREIGN KEY (address_uuid) REFERENCES addresses;
